import { NextRequest } from "next/server";
import { createClient } from "@/lib/supabase/server";

export async function GET(
  request: NextRequest,
  { params }: { params: Promise<{ id: string }> },
) {
  const { id } = await params;
  const { searchParams } = new URL(request.url);
  const format = searchParams.get("format") || "markdown";

  const supabase = await createClient();
  const { data: { user } } = await supabase.auth.getUser();
  if (!user) {
    return Response.json({ error: "Unauthorized" }, { status: 401 });
  }

  const { data: analysis, error } = await supabase
    .from("analyses")
    .select("*")
    .eq("id", id)
    .eq("user_id", user.id)
    .maybeSingle();

  if (error || !analysis) {
    return Response.json({ error: "Not found" }, { status: 404 });
  }

  if (format === "json") {
    return new Response(JSON.stringify(analysis.results, null, 2), {
      headers: {
        "Content-Type": "application/json",
        "Content-Disposition": `attachment; filename="analysis-${id}.json"`,
      },
    });
  }

  // Markdown export
  const md = buildMarkdown(analysis);
  return new Response(md, {
    headers: {
      "Content-Type": "text/markdown; charset=utf-8",
      "Content-Disposition": `attachment; filename="analysis-${id}.md"`,
    },
  });
}

function buildMarkdown(analysis: Record<string, unknown>): string {
  const r = analysis.results as Record<string, unknown>;
  const isUrl = analysis.content_type === "url";
  const lines: string[] = [];

  lines.push("# GEO Analysis Report");
  lines.push("");
  lines.push(`- **Date**: ${new Date(analysis.created_at as string).toISOString().split("T")[0]}`);
  lines.push(`- **Type**: ${isUrl ? "URL Verification" : "Text Quality"}`);
  lines.push(`- **Score**: ${analysis.score}`);

  if (isUrl && r.userUrl) {
    lines.push(`- **URL**: ${r.userUrl}`);
    lines.push(`- **Domain**: ${r.userDomain}`);
  }
  if (r.topic) lines.push(`- **Topic**: ${r.topic}`);
  lines.push("");

  // Content stats
  const stats = r.contentStats as Record<string, number> | undefined;
  if (stats) {
    lines.push("## Content Statistics");
    lines.push("");
    lines.push(`| Metric | Value |`);
    lines.push(`|--------|-------|`);
    if (stats.wordCount) lines.push(`| Words | ${stats.wordCount} |`);
    if (stats.charCount) lines.push(`| Characters | ${stats.charCount} |`);
    if (stats.sentenceCount) lines.push(`| Sentences | ${stats.sentenceCount} |`);
    if (stats.paragraphCount) lines.push(`| Paragraphs | ${stats.paragraphCount} |`);
    lines.push("");
  }

  // Strategy scores
  const strategies = r.strategyScores as Array<{ label: string; score: number; suggestions: string[] }> | undefined;
  if (strategies?.length) {
    lines.push("## Strategy Scores");
    lines.push("");
    lines.push("| Strategy | Score |");
    lines.push("|----------|-------|");
    for (const s of strategies) {
      lines.push(`| ${s.label} | ${s.score}/100 |`);
    }
    lines.push("");
  }

  // Query results (URL mode)
  const queryResults = r.queryResults as Array<Record<string, unknown>> | undefined;
  if (isUrl && queryResults?.length) {
    lines.push("## Query Verification Results");
    lines.push("");
    for (const qr of queryResults) {
      const cited = (qr.citationRate as number) > 0;
      lines.push(`### ${qr.query}`);
      lines.push(`- Cited: ${cited ? "Yes" : "No"} (${qr.citedByEngines}/${qr.totalEngines} engines)`);
      lines.push("");
    }
  }

  // Competitors
  const competitors = r.topCompetitors as Array<{ domain: string; queryCount: number; engineCount: number }> | undefined;
  if (isUrl && competitors?.length) {
    lines.push("## Top Competitors");
    lines.push("");
    lines.push("| Rank | Domain | Queries | Engines |");
    lines.push("|------|--------|---------|---------|");
    competitors.slice(0, 10).forEach((c, i) => {
      lines.push(`| ${i + 1} | ${c.domain} | ${c.queryCount} | ${c.engineCount} |`);
    });
    lines.push("");
  }

  // Suggestions
  const suggestions = r.suggestions as string[] | undefined;
  if (suggestions?.length) {
    lines.push("## Optimization Suggestions");
    lines.push("");
    lines.push(suggestions.join("\n"));
    lines.push("");
  }

  lines.push("---");
  lines.push("*Generated by DeepZD GEO Analysis*");

  return lines.join("\n");
}
